server:
  port: 8080

spring:
  application:
    name: ProxyService

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://127.0.0.1:8081
              predicates:
                - Path=/auth/**
                - Method=POST
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 15
                    redis-rate-limiter.requestedTokens: 1

            - id: catalog-service
              uri: http://127.0.0.1:8091
              predicates:
                - Path=/catalog/**
                - Method=GET
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 15
                    redis-rate-limiter.requestedTokens: 1
                - name: AuthFilter

            - id: admin-catalog-service
              uri: http://localhost:8091
              predicates:
                - Path=/catalog/**
                - Method=POST
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 15
                    redis-rate-limiter.requestedTokens: 1
                - name: AuthFilter
                - name: AdminFilter