server:
  port: 8080

spring:
  application:
    name: ProxyService

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://127.0.0.1:8081
              predicates:
                - Path=/auth/**
                - Method=GET,POST
              filters:
                - name: DemoGatewayFilter
                - name: RequestRateLimiter
                  args:
                    denyEmptyKey: false
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 15
                    redis-rate-limiter.requestedTokens: 1

            - id: node-server
              uri: http://127.0.0.1:3000
              predicates:
                - Path=/node/**
                - Method=GET
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 15
                    redis-rate-limiter.requestedTokens: 1
